<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RoboSync.Core\RoboSync.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\RoboSync.ico" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\RoboSync.ico</ApplicationIcon>
    <Product>RoboSync</Product>
    <AssemblyTitle>RoboSync</AssemblyTitle>
    <Description>A friendly Robocopy front-end for Windows.</Description>
    <Company>navanem.com</Company>
    <Version>1.0.1</Version>
    <Copyright>Copyright (c) 2026 navanem.com</Copyright>
  </PropertyGroup>

</Project>
